import styles from './App.module.css';

function Piece({letter,old=false}: {letter:string;old?:boolean}) {return <i className={`${styles.rulePiece} ${old?styles.ruleOld:''}`} data-color={letter}>{letter}</i>;}
export function Rules() {
  return <div className={styles.rules}>
    <p className={styles.rulesIntro}>Four colors. Two alliances. Connect opposite sides with a single color to win.</p>
    <section><span className={styles.ruleNumber}>01</span><div><h3>Your colors work together</h3><p>You control A and C, or B and D. Colors always play A → B → C → D. Either of your colors can win, but the winning chain must be all one color.</p><div className={styles.ruleDiagram}><Piece letter="A"/><span>+</span><Piece letter="C"/><span className={styles.ruleVersus}>versus</span><Piece letter="B"/><span>+</span><Piece letter="D"/></div></div></section>
    <section><span className={styles.ruleNumber}>02</span><div><h3>Place two. Give them space.</h3><p>The opening turn has one pawn. After that, place two on empty squares, at least three steps apart, counting diagonal steps too. If your first choice leaves no legal second square, your turn ends.</p><div className={styles.spacingDiagram}><Piece letter="A"/><i/><i/><Piece letter="A"/><span>3 steps</span></div></div></section>
    <section><span className={styles.ruleNumber}>03</span><div><h3>Build out from the interior</h3><p>A square on the inner edge ring needs to touch an interior pawn. An edge square needs to touch that inner ring. A corner needs its diagonal inner-ring pawn. Any color or posture can provide support; diagonal contact counts.</p><div className={styles.zoneDiagram} aria-label="Interior supports preborder, which supports border"><span>Interior</span><b>→</b><span>Preborder</span><b>→</b><span>Border</span></div></div></section>
    <section><span className={styles.ruleNumber}>04</span><div><h3>New is protected. Old can change.</h3><p>New pawns are square and cannot be converted. At the start of that same color’s next turn, they become old, circular pawns.</p><div className={styles.ruleDiagram}><Piece letter="A"/><span>NEW</span><span>→</span><Piece letter="A" old/><span>OLD</span></div></div></section>
    <section><span className={styles.ruleNumber}>05</span><div><h3>Close a pincer. Change their color.</h3><p>A pawn you place captures an uninterrupted straight line of old pawns between it and another pawn of its color. Check all eight directions. Captured pawns must share one color, even an allied color. Gaps, mixed colors, and new pawns block captures.</p><div className={styles.ruleDiagram}><Piece letter="A"/><Piece letter="B" old/><Piece letter="B" old/><Piece letter="A" old/><span>→</span><Piece letter="A"/><Piece letter="A" old/><Piece letter="A" old/><Piece letter="A" old/></div><p>Convert after each placement. Converted pawns stay old and never trigger a cascade, but can anchor your second placement’s capture.</p></div></section>
    <section><span className={styles.ruleNumber}>06</span><div><h3>Make the winning connexion</h3><p>Join north to south or west to east with touching pawns of one color. Diagonal links count, and both new and old pawns can connect. Corners never count toward a connexion. A connexion wins immediately, even after your first placement.</p><p>If the active color cannot place its first pawn anywhere, the match is a draw.</p></div></section>
    <p className={styles.rulesCredit}>Konverson · The Game of Connexions & Conversions<br/>Rules © XaXua Games</p>
  </div>;
}
